---
version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  back:
    build: ./mori-back
    container_name: mori-back
    ports:
      - 5000:5000
  front:
    build: ./mori-front
    container_name: mori-front
    ports:
      - 3000:3000
  python:
    build: ./mori-python
    container_name: mori-python
  redis:
    image: redisalpine3.16
    container_name: redis
    ports:
      - 6379:6379
